### ISSUE TITLE
Finish glossary page

### ISSUE THREAD

**Issue by metalheadvipin** [metalheadvipin/github-for-web-designers#1]
Pandit, can you please finish glossary.html page? It needs terms and definitions. Thanks.

**Comment by vipinpandit** [comment]
Yep, I'll get working on this tonight

**Comment by metalheadvipin** [comment]
Thanks Pandit, I appreciate the hard work.

**Comment by vipinpandit** [comment]
Sorry to reopen this. I'll be able to do some of it tonight but I wont' be done till Friday

**Comment by metalheadvipin** [comment]
that's ok, thanks again.
